Repository kratsg/github-action-test, pull requests merged in 2019-11, with the labels that each got.

#14 docs: add more text to readme
  .github/workflows/tag.yml
  README
Labels: bumpversion/minor, documentation

#16 feat: Create a test
  a-test-i-say.txt
Labels: bumpversion/minor

#15 feat: something new
  .github/workflows/tag.yml
  README
Labels: bumpversion/patch

#17 ci: test push
  .github/workflows/tag.yml
Labels: bumpversion/minor
